// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2024-2026 ecoPrimals

//! Service registry, capability discovery, and health JSON-RPC types (v3.20.0).

use serde::{Deserialize, Serialize};

/// Request to register a primal service with Songbird
///
/// ## Example
///
/// ```json
/// {
///   "jsonrpc": "2.0",
///   "method": "register_service",
///   "params": {
///     "primal_name": "security provider",
///     "capabilities": ["encryption", "identity", "trust"],
///     "endpoint": "/run/user/1000/security-provider-nat0.sock",
///     "protocol": "json-rpc",
///     "health_check_interval": 30
///   },
///   "id": 4
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegisterServiceRequest {
    /// Primal name (e.g., "`security provider`", "`ToadStool`")
    pub primal_name: String,

    /// Capabilities provided (e.g., ["encryption", "identity"])
    pub capabilities: Vec<String>,

    /// Endpoint (e.g., "/run/user/1000/security-provider-nat0.sock")
    pub endpoint: String,

    /// Protocol (e.g., "json-rpc", "tarpc", "http")
    pub protocol: String,

    /// Health check interval in seconds (optional, default: 30)
    #[serde(default = "default_health_interval")]
    pub health_check_interval: u64,
}

const fn default_health_interval() -> u64 {
    30
}

/// Response after registering a service
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegisterServiceResponse {
    /// Unique service ID (auto-generated by Songbird)
    pub service_id: String,

    /// Status ("registered", "updated", "failed")
    pub status: String,

    /// When the service was registered (ISO 8601)
    pub registered_at: String,
}

/// Request to discover primals by capability
///
/// ## Example
///
/// ```json
/// {
///   "jsonrpc": "2.0",
///   "method": "discover_by_capability",
///   "params": {
///     "capability": "encryption",
///     "protocol": "json-rpc"
///   },
///   "id": 5
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiscoverByCapabilityRequest {
    /// Capability to search for (e.g., "encryption", "storage", "*" for all)
    pub capability: String,

    /// Optional protocol filter (e.g., "json-rpc", "tarpc")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
}

/// Response containing discovered primals
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiscoverByCapabilityResponse {
    /// Discovered primals matching the capability
    pub primals: Vec<PrimalEndpoint>,
}

/// Primal endpoint information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PrimalEndpoint {
    /// Unique service ID (auto-generated by Songbird)
    pub service_id: String,

    /// Primal name
    pub primal_name: String,

    /// Capabilities
    pub capabilities: Vec<String>,

    /// Endpoint (Unix socket path or URL)
    pub endpoint: String,

    /// Protocol
    pub protocol: String,

    /// Last health check timestamp (ISO 8601)
    pub last_health_check: String,

    /// Health status ("healthy", "degraded", "down", "unknown")
    pub health_status: String,
}

/// Request for `capability.resolve` — single-step DNS-like routing by capability.
///
/// Returns the best provider endpoint for the requested capability, matching
/// the universal-ipc `capability.resolve` wire format.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CapabilityResolveRequest {
    /// Capability domain to resolve (e.g. "crypto", "storage", "compute")
    pub capability: String,
}

/// Response for `capability.resolve` — the single best provider for the capability.
///
/// Wire-format harmonized with universal-ipc `CapabilityResolveResult`: both paths
/// now emit `socket`, `native_endpoint`, `virtual_endpoint`, `transport`, and `capabilities`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CapabilityResolveResponse {
    /// Service ID of the resolved provider
    pub service_id: String,
    /// Primal name that owns this capability
    pub primal_name: String,
    /// Endpoint (Unix socket path or URL) — legacy field, prefer `transport`
    pub endpoint: String,
    /// Protocol (json-rpc, tarpc, etc.)
    pub protocol: String,
    /// Bare socket path (e.g. `/run/user/1000/biomeos/security.sock`).
    /// Present when the provider uses a Unix socket transport.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub socket: Option<String>,
    /// Transport-qualified URI (e.g. `unix:///path/to/sock`, `tcp://127.0.0.1:8080`).
    pub native_endpoint: String,
    /// Structured transport endpoint (Phase 2). Consumers should prefer this.
    pub transport: songbird_universal_ipc::TransportEndpoint,
    /// Capability-addressed virtual endpoint (e.g. `capability://crypto@beardog`).
    pub virtual_endpoint: String,
    /// All capabilities advertised by this provider
    pub capabilities: Vec<String>,
}

/// Request to get health status of a specific service
///
/// ## Example
///
/// ```json
/// {
///   "jsonrpc": "2.0",
///   "method": "get_service_health",
///   "params": {
///     "service_id": "security-provider-12345"
///   },
///   "id": 6
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetServiceHealthRequest {
    /// Service ID to check
    pub service_id: String,
}

/// Response with health status
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetServiceHealthResponse {
    /// Health status
    pub health: HealthStatus,
}

/// Health status information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthStatus {
    /// Service ID (or "songbird" for Songbird itself)
    pub service_id: String,

    /// Status ("healthy", "degraded", "down", "unknown")
    pub status: String,

    /// Optional message (e.g., error reason)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    /// Timestamp (ISO 8601)
    pub timestamp: String,
}

/// Request for Songbird's own health check
///
/// ## Example
///
/// ```json
/// {
///   "jsonrpc": "2.0",
///   "method": "health_check",
///   "params": {},
///   "id": 7
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthCheckRequest {}

/// Response with Songbird's health
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthCheckResponse {
    /// Health status
    pub health: HealthStatus,
}
