// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2024-2026 ecoPrimals

//! # 🌐 Songbird Universal Orchestration
//!
//! **UNIFIED UNIVERSAL ADAPTER SYSTEM** ✅
//!
//! This crate provides universal, vendor-agnostic orchestration capabilities
//! that can work with any primal or service provider through capability-based discovery.
#![forbid(unsafe_code)]
#![warn(missing_docs)]
#![warn(clippy::all)]
#![allow(
    clippy::significant_drop_tightening,
    reason = "Phase 2: tighten drops after adapter graph stabilizes"
)]
#![allow(
    clippy::cognitive_complexity,
    reason = "Phase 2: split orchestration paths when feature set settles"
)]
#![allow(
    clippy::if_same_then_else,
    reason = "Phase 2: branch symmetry kept for readability during refactors"
)]
#![allow(
    clippy::needless_borrow,
    reason = "Phase 2: borrow style unified with surrounding adapter code"
)]
#![allow(
    clippy::missing_fields_in_debug,
    reason = "Phase 2: complete Debug for all public adapter types"
)]
#![cfg_attr(
    test,
    allow(
        deprecated,
        dead_code,
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::await_holding_lock,
        clippy::float_cmp,
        clippy::absurd_extreme_comparisons,
        clippy::nonminimal_bool,
        clippy::needless_collect,
        clippy::used_underscore_binding,
        clippy::overly_complex_bool_expr,
        clippy::assertions_on_constants,
        clippy::unreadable_literal,
        clippy::empty_line_after_doc_comments,
        clippy::field_reassign_with_default,
        clippy::unnecessary_wraps,
        clippy::no_effect_underscore_binding,
        clippy::return_self_not_must_use,
        clippy::duplicated_attributes,
        clippy::needless_pass_by_value,
        clippy::must_use_candidate,
        clippy::missing_panics_doc,
        clippy::missing_errors_doc,
        clippy::doc_markdown,
        clippy::wildcard_imports,
        clippy::enum_glob_use,
        unused_imports,
        unused_variables,
        clippy::unused_self,
        clippy::unnecessary_cast,
        clippy::items_after_test_module,
        clippy::clone_on_ref_ptr,
        clippy::default_trait_access,
        clippy::needless_range_loop,
        clippy::similar_names,
        clippy::cast_possible_truncation,
        clippy::cast_sign_loss,
        clippy::unnecessary_unwrap,
        clippy::ignore_without_reason,
        clippy::case_sensitive_file_extension_comparisons,
    )
)]

// ============================================================================
// UNIFIED ADAPTER SYSTEM - Primary Interface
// ============================================================================

pub mod adapters;
// NOTE: btsp_client moved to songbird-orchestrator (v3.20.0, Jan 16, 2026)
// New Unix socket-based implementation in songbird-orchestrator/src/btsp_client.rs
pub mod btsp_types; // BTSP (BirdSong Transport Protocol) types (v3.15.1)
pub mod capabilities;
pub mod circuit_breaker;
pub mod circuit_breaker_manager; // ✅ NEW (Feb 3, 2026): Modern circuit breaker manager for external calls
pub mod discovery;
pub mod federated_capability_adapter;
pub mod jsonrpc_client;
pub mod load_balancer;
pub mod sovereignty;
pub mod tarpc_client;
pub mod tarpc_types;
pub mod traits;
pub mod trust_types;
#[cfg(test)]
mod trust_types_phase1_tests;
pub mod types;
pub mod unified_adapter;
pub mod unix_rpc_client; // Pure Rust Unix socket JSON-RPC client (v3.35.0)

// NOTE: zero_knowledge_bootstrap removed - will be properly reimplemented in Phase 2B
// with modern idiomatic Rust patterns. Feature tracked in IMPLEMENTATION_CHECKLIST.md

// Re-export the unified adapter as the primary interface
pub use unified_adapter::{
    CapabilityRegistry, RegistryStats, ServiceConnection, UnifiedAdapterConfig,
    UnifiedUniversalAdapter, UniversalAdapterError,
};

// Re-export modernized sovereignty system
pub use sovereignty::{
    PathSegment, RoutingPath, SovereigntyAdapterConfig, SovereigntyAwareAdapter,
    SovereigntyAwareRoutingDecision,
};

// Re-export core types
pub use types::*;

// Explicitly re-export capability types to avoid confusion
pub use capabilities::Capability as CapabilityDefinition;
pub use types::DiscoveredCapability;

// Re-export JSON-RPC clients for protocol-agnostic communication
pub use jsonrpc_client::JsonRpcClient;
pub use unix_rpc_client::UnixRpcClient; // Pure Rust Unix socket RPC!

// Re-export tarpc types and client for high-performance primal-to-primal RPC (v3.12.0)
pub use tarpc_client::TarpcClient;
pub use tarpc_types::{
    HealthStatus as TarpcHealthStatus,
    ProtocolInfo as TarpcProtocolInfo,
    RegistrationResult as TarpcRegistrationResult,
    ServiceInfo as TarpcServiceInfo,
    ServiceRegistration as TarpcServiceRegistration,
    SongbirdRpc,       // Re-exported for server implementations
    SongbirdRpcClient, // Generated by tarpc macro
    VersionInfo as TarpcVersionInfo,
};

// Re-export trust evaluation types for inter-primal trust evaluation (v3.12.3)
// NOTE: BtspClient moved to songbird-orchestrator (v3.20.0, Jan 16, 2026)
// Use: use songbird_orchestrator::btsp_client::BtspClient;
pub use btsp_types::{
    BtspEndpoint, BtspTunnel, BtspTunnelRequest, BtspTunnelResponse, ContactExchangeRequest,
    ContactExchangeResponse, PeerContact, TunnelState, TunnelType,
};
pub use trust_types::{IdentityResponse, TrustEvaluationRequest, TrustEvaluationResponse};

/// Create a new unified universal adapter with default configuration
#[must_use]
pub fn create_universal_adapter() -> UnifiedUniversalAdapter {
    UnifiedUniversalAdapter::new()
}

/// Create a new unified universal adapter with custom configuration
#[must_use]
pub fn create_universal_adapter_with_config(
    config: UnifiedAdapterConfig,
) -> UnifiedUniversalAdapter {
    UnifiedUniversalAdapter::with_config(config)
}

#[cfg(test)]
mod lib_tests {
    use super::*;

    #[test]
    fn test_create_universal_adapter() {
        let adapter = create_universal_adapter();
        // Verify adapter is created and functional
        assert!(format!("{:?}", adapter).contains("UnifiedUniversalAdapter"));
    }

    #[test]
    fn test_create_universal_adapter_with_custom_config() {
        let config = UnifiedAdapterConfig {
            discovery_timeout: std::time::Duration::from_secs(10),
            health_check_interval: std::time::Duration::from_secs(30),
            max_concurrent_requests: 100,
            auto_discovery: true,
            discovery_endpoints: vec!["http://localhost:8080".to_string()],
        };

        let adapter = create_universal_adapter_with_config(config);
        // Verify adapter is created with custom config
        assert!(format!("{:?}", adapter).contains("UnifiedUniversalAdapter"));
    }

    #[test]
    fn test_module_exports_compile() {
        // Verify key types are exported and accessible at compile time
        fn _check_types() {
            let _adapter: UnifiedUniversalAdapter = create_universal_adapter();
            let _config = UnifiedAdapterConfig::default();
            let _registry = CapabilityRegistry::default();
            let _connection: Option<ServiceConnection> = None;
            let _stats: Option<RegistryStats> = None;
        }
    }

    #[test]
    fn test_unified_adapter_config_default() {
        let config = UnifiedAdapterConfig::default();
        // Verify default values are reasonable
        assert!(config.discovery_timeout.as_secs() > 0);
        assert!(config.health_check_interval.as_secs() > 0);
        assert!(config.max_concurrent_requests > 0);
    }

    #[test]
    fn test_capability_definition_reexport() {
        // Verify CapabilityDefinition is accessible
        fn _check_capability_def(_cap: CapabilityDefinition) {}
    }
}
