#!/bin/bash
# 🚀 Hardcoding Elimination Script
# Systematically replaces hardcoded localhost/IP references with environment-based config

set -euo pipefail

REPO_ROOT="/home/eastgate/Development/ecoPrimals/songbird"
cd "$REPO_ROOT"

echo "🔍 Starting hardcoding elimination..."
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Counter
total_replaced=0

# Function to replace in file
replace_in_file() {
    local file="$1"
    local pattern="$2"
    local replacement="$3"
    local description="$4"
    
    if grep -q "$pattern" "$file" 2>/dev/null; then
        echo -e "${YELLOW}Found in${NC} $file"
        echo "  Replacing: $description"
        
        # Create backup
        cp "$file" "$file.bak"
        
        # Perform replacement
        sed -i "s|$pattern|$replacement|g" "$file"
        
        # Count replacements
        local count=$(grep -c "$replacement" "$file" || echo "0")
        ((total_replaced+=count))
        
        echo -e "${GREEN}  ✓ Replaced $count instances${NC}"
    fi
}

echo "📋 Phase 1: Replace deprecated primal endpoint constants"
echo "-------------------------------------------------------"

# Find all files using deprecated constants
echo ""
echo "Finding usages of deprecated constants..."

# Replace DEFAULT_BEARDOG_ENDPOINT
for file in $(grep -r "DEFAULT_BEARDOG_ENDPOINT" crates/*/src --include="*.rs" -l 2>/dev/null || true); do
    replace_in_file "$file" \
        "DEFAULT_BEARDOG_ENDPOINT" \
        'get_primal_endpoint("beardog")' \
        "BearDog endpoint"
done

# Replace DEFAULT_NESTGATE_ENDPOINT
for file in $(grep -r "DEFAULT_NESTGATE_ENDPOINT" crates/*/src --include="*.rs" -l 2>/dev/null || true); do
    replace_in_file "$file" \
        "DEFAULT_NESTGATE_ENDPOINT" \
        'get_primal_endpoint("nestgate")' \
        "NestGate endpoint"
done

# Replace DEFAULT_TOADSTOOL_ENDPOINT
for file in $(grep -r "DEFAULT_TOADSTOOL_ENDPOINT" crates/*/src --include="*.rs" -l 2>/dev/null || true); do
    replace_in_file "$file" \
        "DEFAULT_TOADSTOOL_ENDPOINT" \
        'get_primal_endpoint("toadstool")' \
        "ToadStool endpoint"
done

# Replace DEFAULT_SQUIRREL_ENDPOINT
for file in $(grep -r "DEFAULT_SQUIRREL_ENDPOINT" crates/*/src --include="*.rs" -l 2>/dev/null || true); do
    replace_in_file "$file" \
        "DEFAULT_SQUIRREL_ENDPOINT" \
        'get_primal_endpoint("squirrel")' \
        "Squirrel endpoint"
done

echo ""
echo "📋 Phase 2: Replace hardcoded localhost URLs in tests"
echo "-------------------------------------------------------"

# This is more conservative - only replace in test files
for file in $(grep -r '"http://localhost:' crates/*/src --include="*.rs" -l 2>/dev/null || true); do
    # Check if it's a test file
    if grep -q "#\[test\]" "$file" || grep -q "#\[cfg(test)\]" "$file"; then
        echo -e "${YELLOW}Test file:${NC} $file"
        echo "  Adding comment about localhost usage in tests"
        # Tests can keep localhost but should have comments
        sed -i 's|"http://localhost:|// Test uses localhost - acceptable for unit tests\n    "http://localhost:|g' "$file"
    fi
done

echo ""
echo "📋 Phase 3: Generate environment configuration template"
echo "-------------------------------------------------------"

cat > .env.hardcoding-eliminated <<'EOF'
# 🚀 Songbird Configuration - Zero Hardcoding
# Generated by hardcoding elimination script

# === Primal Discovery ===
# Use "capability:TYPE" for auto-discovery or specify explicit endpoints

# Security Primal (BearDog)
BEARDOG_ENDPOINT=capability:security
# Or: BEARDOG_ENDPOINT=http://beardog-service:8004

# Storage Primal (NestGate)
NESTGATE_ENDPOINT=capability:storage
# Or: NESTGATE_ENDPOINT=http://nestgate-service:8003

# Compute Primal (ToadStool)
TOADSTOOL_ENDPOINT=capability:compute
# Or: TOADSTOOL_ENDPOINT=http://toadstool-service:8001

# AI Primal (Squirrel)
SQUIRREL_ENDPOINT=capability:ai
# Or: SQUIRREL_ENDPOINT=http://squirrel-service:8002

# === Network Configuration ===
SONGBIRD_HOST=127.0.0.1              # Development default
SONGBIRD_BIND_ADDRESS=0.0.0.0         # Bind to all interfaces
SONGBIRD_ENV=development               # Or: production, staging, testing

# === Port Configuration ===
SONGBIRD_PORT_START=8000
SONGBIRD_PORT_END=9000
SONGBIRD_ORCHESTRATOR_PORT=8080

# === Discovery Configuration ===
SONGBIRD_ENABLE_DISCOVERY=true
SONGBIRD_DISCOVERY_PORT=5678

# === Enablement Flags ===
SONGBIRD_ENABLE_BEARDOG=true
SONGBIRD_ENABLE_NESTGATE=true
SONGBIRD_ENABLE_TOADSTOOL=true
SONGBIRD_ENABLE_SQUIRREL=true

EOF

echo -e "${GREEN}✓ Created .env.hardcoding-eliminated template${NC}"

echo ""
echo "📋 Phase 4: Summary"
echo "-------------------------------------------------------"
echo ""
echo "Total replacements made: $total_replaced"
echo ""
echo "✅ Hardcoding elimination complete!"
echo ""
echo "Next steps:"
echo "1. Review the changes in git diff"
echo "2. Run: cargo test --workspace"
echo "3. Copy .env.hardcoding-eliminated to .env"
echo "4. Test with: cargo run"
echo ""
echo "Backup files created with .bak extension"
echo "To restore: find crates/ -name '*.bak' -exec bash -c 'mv \"\$0\" \"\${0%.bak}\"' {} \;"

